name: core-ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test-core:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Go version
        run: go version

      - name: Go env
        run: go env

      - name: Vet (all)
        run: go vet ./...

      - name: Test (all)
  run: go test -v ./... -timeout 20m

      - name: Test with race detector (all)
        run: go test -race -v ./... -timeout 20m
